package main

const aliasTemplate = `// nolint
// DO NOT EDIT Code generated by aliasgen tool (github.com/rhuairahrighairidh/aliasgen).
package {{.PackageName}}
{{ if .Imports }}
import ({{ range .Imports }}
	"{{.}}"{{end}}
)
{{end -}}

{{ if .Consts }}
const ({{ range .Consts }}
	{{.Name}} = {{.Pkg}}.{{.Name}}{{end}}
)
{{end -}}

{{if .HasVarsOrFuncs}}
var ({{if .Funcs}}
	// function aliases{{ range .Funcs }}
	{{.Name}} = {{.Pkg}}.{{.Name}}{{end}}{{end}}{{if .HasVarsAndFuncs}}
{{end}}{{if .Vars}}
	// variable aliases{{ range .Vars }}
	{{.Name}} = {{.Pkg}}.{{.Name}}{{end}}{{end}}
)
{{end -}}

{{ if .Types }}
type ({{ range .Types }}
	{{.Name}} = {{.Pkg}}.{{.Name}}{{end}}
)
{{end}}
`

// type AliasedGroup struct {
// 	ContainingPackageName string
// 	AliasedPackages       []AliasedPackage
// }

// type AliasedPackage struct {
// 	Name       string
// 	ImportPath string
// 	Consts     []string
// 	Vars       []string
// 	Funcs      []string
// 	Types      []string
// }

type TemplateData struct {
	PackageName string
	Imports     []string
	Consts      []Alias
	Vars        []Alias
	Funcs       []Alias
	Types       []Alias
}

func (td TemplateData) HasVarsOrFuncs() bool {
	return len(td.Vars) > 0 || len(td.Funcs) > 0
}
func (td TemplateData) HasVarsAndFuncs() bool {
	return len(td.Vars) > 0 && len(td.Funcs) > 0
}

type Alias struct {
	Pkg  string
	Name string
}
